%%
% Tom-Avi Shapira
% Lital Yakobov

%%
function [statisticsMat] = analizeOutput( output )

%% display results
    output1 = output(:,2);
    output2 = output(:,1);
    
    time = 10.5:0.5:10+size(output1,1)/2;
    
    xLine = [15 20 26 32 38 41 44.5 47.5 51 55.5 60];
    
    
    figure();
    stem(time,output1,'r-o');
    hold on;
    stem(time,output2,'b-*');
    for i=1 : length(xLine)
        hold on;
        plot([xLine(i) xLine(i)], get(gca, 'ylim'),'g','LineWidth',2);
    end
    grid on;
    yticks([1 2 3 4 5 6 7 8 9 10]);
    xticks(time);
    xtickangle(90);
    legend('right eye','left eye');

    
%% create expected output mat
    expectedOutputMat = [ 1 -1 -1 -1 ;...
                          1 -1 -1 -1 ;...
                          2 3 -1 -1 ;...
                          2 3 -1 -1 ;...
                          4 5 6 -1 ;...
                          4 5 6 -1 ;...
                          7 -1 -1 -1 ;...
                          7 -1 -1 -1 ;...
                          8 9 10 -1 ;...
                          8 9 10 -1 ;...
                          1 2 3 -1 ;...
                          1 2 3 -1 ;...
                          4 -1 -1 -1 ;...
                          4 -1 -1 -1 ;...
                          5 -1 -1 -1 ;...
                          5 -1 -1 -1  ;...
                          6 7 8 -1 ;...
                          6 7 8 -1 ;...
                          9 10 -1 -1 ;...
                          9 10 -1 -1 ;...
                          1 -1 -1 -1  ;...
                          1 -1 -1 -1  ;...
                          2 3 -1 -1 ;...
                          2 3 -1 -1 ;...
                          4 -1 -1 -1 ;...
                          4 -1 -1 -1 ;...
                          5 -1 -1 -1 ;...
                          5 -1 -1 -1 ;...
                          6 -1 -1 -1 ;...
                          6 -1 -1 -1 ;...
                          7 8 9 10 ;...
                          7 8 9 10 ;...
                          1 -1 -1 -1 ;...
                          1 -1 -1 -1 ;...
                          2 -1 -1 -1 ;...
                          2 -1 -1 -1 ;...
                          3 4 5 -1 ;...
                          3 4 5 -1 ;...
                          6 -1 -1 -1 ;...
                          6 -1 -1 -1 ;...
                          7 -1 -1 -1 ;...
                          7 -1 -1 -1 ;...
                          8 9 10 -1 ;...
                          8 9 10 -1 ;...
                          1 2 3 -1 ;...
                          1 2 3 -1 ;...
                          4 -1 -1 -1 ;...
                          4 -1 -1 -1 ;...
                          5 6 -1 -1 ;...
                          5 6 -1 -1 ;...
                          7 -1 -1 -1 ;...
                          7 -1 -1 -1 ;...
                          8 -1 -1 -1 ;...
                          8 -1 -1 -1 ;...
                          9 10 -1 -1 ;...
                          9 10 -1 -1 ;...
                          1 2 3 -1 ;...
                          4 -1 -1 -1 ;...
                          5 6 -1 -1 ;...
                          7 -1 -1 -1 ;...
                          8 9 -1 -1 ;...
                          10 -1 -1 -1 ;...
                          1 -1 -1 -1  ;...
                          2 3 -1 -1 ;...
                          4 -1 -1 -1  ;...
                          5 6 -1 -1 ;...
                          7 -1 -1 -1 ;...
                          8 -1 -1 -1 ;...
                          9 10 -1 -1 ;...
                          1 2 -1 -1 ;...
                          3 4 -1 -1 ;...
                          5 -1 -1 -1 ;...
                          6 -1 -1 -1 ;...
                          7 8 -1 -1 ;...
                          9 10 -1 -1 ;...
                          1 -1 -1 -1 ;...
                          2 -1 -1 -1 ;...
                          3 4 -1 -1 ;...
                          5 -1 -1 -1 ;...
                          6 -1 -1 -1 ;...
                          7 8 -1 -1 ;...
                          9 10 -1 -1 ;...
                          1 -1 -1 -1 ;...
                          2 -1 -1 -1 ;...
                          3 -1 -1 -1 ;...
                          4 -1 -1 -1 ;...
                          5 -1 -1 -1 ;...
                          6 7 -1 -1 ;...
                          8 -1 -1 -1 ;...
                          9 -1 -1 -1 ;...
                          10 -1 -1 -1 ;...
                          1 -1 -1 -1 ;...
                          2 -1 -1 -1 ;...
                          3 -1 -1 -1 ;...
                          4 -1 -1 -1 ;...
                          5 6 -1 -1 ;...
                          7 8 -1 -1 ;...
                          8 -1 -1 -1 ;...
                          9 -1 -1 -1 ;...
                          10 -1 -1 -1];                       

%% analize all video
    [rightEye, leftEye, rightEye_plusMinusOne, leftEye_plusMinusOne] = getStatistics(output, expectedOutputMat);

   %% analize part 1 (velocity 1 sec)
    [part1_rightEye, part1_leftEye, part1_rightEye_plusMinusOne, part1_leftEye_plusMinusOne] = getStatistics(output(1:56,:), expectedOutputMat(1:56,:));
    
%% analize part 2 (velocity 0.5 sec)
 
    [part2_rightEye, part2_leftEye, part2_rightEye_plusMinusOne, part2_leftEye_plusMinusOne] = getStatistics(output(57:end,:), expectedOutputMat(57:end,:));

%% analize word length 1
    ind = [];
    ind1 = [];
    ind2 = [];
    for i=1 : size(expectedOutputMat,1)
        cnt = 0;
        for j=1 : size(expectedOutputMat,2)
            if (expectedOutputMat(i,j) > 0)
                cnt = cnt + 1;
            end
        end
        if (cnt == 1)
            ind = [ind ; i]; % all video
            if (i <= 56)
                ind1 = [ind1 ; i]; % part 1
            else
                ind2 = [ind2 ; i]; % part 2
            end
        end
    end
    [rightEye_all_len1, leftEye_all_len1, rightEye_all_len1_plusMinusOne, leftEye_all_len1_plusMinusOne] = getStatistics(output(ind,:), expectedOutputMat(ind,:));
    [rightEye_part1_len1, leftEye_part1_len1, rightEye_part1_len1_plusMinusOne, leftEye_part1_len1_plusMinusOne] = getStatistics(output(ind1,:), expectedOutputMat(ind1,:));
    [rightEye_part2_len1, leftEye_part2_len1, rightEye_part2_len1_plusMinusOne, leftEye_part2_len1_plusMinusOne] = getStatistics(output(ind2,:), expectedOutputMat(ind2,:));

%% analize word length 2
    ind = [];
    ind1 = [];
    ind2 = [];
    for i=1 : size(expectedOutputMat,1)
        cnt = 0;
        for j=1 : size(expectedOutputMat,2)
            if (expectedOutputMat(i,j) > 0)
                cnt = cnt + 1;
            end
        end
        if (cnt == 2)
            ind = [ind ; i]; % all video
            if (i <= 56)
                ind1 = [ind1 ; i]; % part 1
            else
                ind2 = [ind2 ; i]; % part 2
            end
        end
    end
    [rightEye_all_len2, leftEye_all_len2, rightEye_all_len2_plusMinusOne, leftEye_all_len2_plusMinusOne] = getStatistics(output(ind,:), expectedOutputMat(ind,:));
    [rightEye_part1_len2, leftEye_part1_len2, rightEye_part1_len2_plusMinusOne, leftEye_part1_len2_plusMinusOne] = getStatistics(output(ind1,:), expectedOutputMat(ind1,:));
    [rightEye_part2_len2, leftEye_part2_len2, rightEye_part2_len2_plusMinusOne, leftEye_part2_len2_plusMinusOne] = getStatistics(output(ind2,:), expectedOutputMat(ind2,:));

%% analize word length 3
    ind = [];
    ind1 = [];
    ind2 = [];
    for i=1 : size(expectedOutputMat,1)
        cnt = 0;
        for j=1 : size(expectedOutputMat,2)
            if (expectedOutputMat(i,j) > 0)
                cnt = cnt + 1;
            end
        end
        if (cnt == 3)
            ind = [ind ; i]; % all video
            if (i <= 56)
                ind1 = [ind1 ; i]; % part 1
            else
                ind2 = [ind2 ; i]; % part 2
            end
        end
    end
    [rightEye_all_len3, leftEye_all_len3, rightEye_all_len3_plusMinusOne, leftEye_all_len3_plusMinusOne] = getStatistics(output(ind,:), expectedOutputMat(ind,:));
    [rightEye_part1_len3, leftEye_part1_len3, rightEye_part1_len3_plusMinusOne, leftEye_part1_len3_plusMinusOne] = getStatistics(output(ind1,:), expectedOutputMat(ind1,:));
    [rightEye_part2_len3, leftEye_part2_len3, rightEye_part2_len3_plusMinusOne, leftEye_part2_len3_plusMinusOne] = getStatistics(output(ind2,:), expectedOutputMat(ind2,:));

%% analize word length 4
    ind = [];
    ind1 = [];
    ind2 = [];
    for i=1 : size(expectedOutputMat,1)
        cnt = 0;
        for j=1 : size(expectedOutputMat,2)
            if (expectedOutputMat(i,j) > 0)
                cnt = cnt + 1;
            end
        end
        if (cnt == 4)
            ind = [ind ; i]; % all video
            if (i <= 56)
                ind1 = [ind1 ; i]; % part 1
            else
                ind2 = [ind2 ; i]; % part 2
            end
        end
    end
    [rightEye_all_len4, leftEye_all_len4, rightEye_all_len4_plusMinusOne, leftEye_all_len4_plusMinusOne] = getStatistics(output(ind,:), expectedOutputMat(ind,:));
    [rightEye_part1_len4, leftEye_part1_len4, rightEye_part1_len4_plusMinusOne, leftEye_part1_len4_plusMinusOne] = getStatistics(output(ind1,:), expectedOutputMat(ind1,:));
    [rightEye_part2_len4, leftEye_part2_len4, rightEye_part2_len4_plusMinusOne, leftEye_part2_len4_plusMinusOne] = getStatistics(output(ind2,:), expectedOutputMat(ind2,:));

%% prepare statistics mat
    statisticsMat = [leftEye leftEye_plusMinusOne rightEye rightEye_plusMinusOne ;...
                     part1_leftEye part1_leftEye_plusMinusOne part1_rightEye part1_rightEye_plusMinusOne ;...
                     part2_leftEye part2_leftEye_plusMinusOne part2_rightEye part2_rightEye_plusMinusOne ;...
                     leftEye_all_len1 leftEye_all_len1_plusMinusOne rightEye_all_len1 rightEye_all_len1_plusMinusOne ;...
                     leftEye_part1_len1 leftEye_part1_len1_plusMinusOne rightEye_part1_len1 rightEye_part1_len1_plusMinusOne ;...
                     leftEye_part2_len1 leftEye_part2_len1_plusMinusOne rightEye_part2_len1 rightEye_part2_len1_plusMinusOne ;...
                     leftEye_all_len2 leftEye_all_len2_plusMinusOne rightEye_all_len2 rightEye_all_len2_plusMinusOne ;...
                     leftEye_part1_len2 leftEye_part1_len2_plusMinusOne rightEye_part1_len2 rightEye_part1_len2_plusMinusOne ;...
                     leftEye_part2_len2 leftEye_part2_len2_plusMinusOne rightEye_part2_len2 rightEye_part2_len2_plusMinusOne ;...
                     leftEye_all_len3 leftEye_all_len3_plusMinusOne rightEye_all_len3 rightEye_all_len3_plusMinusOne ;...
                     leftEye_part1_len3 leftEye_part1_len3_plusMinusOne rightEye_part1_len3 rightEye_part1_len3_plusMinusOne ;...
                     leftEye_part2_len3 leftEye_part2_len3_plusMinusOne rightEye_part2_len3 rightEye_part2_len3_plusMinusOne ;...
                     leftEye_all_len4 leftEye_all_len4_plusMinusOne rightEye_all_len4 rightEye_all_len4_plusMinusOne ;...
                     leftEye_part1_len4 leftEye_part1_len4_plusMinusOne rightEye_part1_len4 rightEye_part1_len4_plusMinusOne ;...
                     leftEye_part2_len4 leftEye_part2_len4_plusMinusOne rightEye_part2_len4 rightEye_part2_len4_plusMinusOne];
end

